In [2]:
import pandas as pd

df = pd.read_csv('aice_day3_customer_churn.csv')

In [3]:
df.head()

,customer_id,age,gender,city,monthly_fee,usage_hours,login_count,support_calls,contract_months,churn
0,C001,NaN,M,대구,40000,35.3,29,0,1,0
1,C002,58.0,M,서울,80000,9.3,12,0,3,1
2,C003,30.0,F,부산,35000,36.4,29,3,6,0
3,C004,54.0,M,울산,55000,39.0,23,2,24,0
4,C005,34.0,F,울산,40000,39.8,12,0,3,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      120 non-null    str
 1   age              116 non-null    float64
 2   gender           120 non-null    str
 3   city             118 non-null    str
 4   monthly_fee      120 non-null    int64
 5   usage_hours      114 non-null    float64
 6   login_count      120 non-null    int64
 7   support_calls    120 non-null    int64
 8   contract_months  120 non-null    int64
 9   churn            120 non-null    int64
dtypes: float64(2), int64(5), str(3)
memory usage: 9.5 KB

In [22]:
df.isnull().sum()

customer_id          0
age                  0
gender             120
city                 0
monthly_fee          0
usage_hours          0
login_count          0
support_calls        0
contract_months      0
churn                0
dtype: int64

In [8]:
df['age'].median()

np.float64(37.5)

In [9]:
df['age'] = df['age'].fillna(df['age'].median())

In [10]:
df['city'].mode()[0]

'서울'

In [11]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [14]:
df['usage_hours'].describe()

count    114.000000
mean      31.535088
std       11.518473
min        7.000000
25%       22.875000
50%       31.900000
75%       38.700000
max       57.800000
Name: usage_hours, dtype: float64

In [15]:
df['usage_hours'] = df['usage_hours'].fillna(df['usage_hours'].median())

In [17]:
df.isnull().sum()

customer_id        0
age                0
gender             0
city               0
monthly_fee        0
usage_hours        0
login_count        0
support_calls      0
contract_months    0
churn              0
dtype: int64

In [24]:
df['gender']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
115   NaN
116   NaN
117   NaN
118   NaN
119   NaN
Name: gender, Length: 120, dtype: float64

In [25]:
df = pd.read_csv('aice_day3_customer_churn.csv')

In [26]:
df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])
df['usage_hours'] = df['usage_hours'].fillna(df['usage_hours'].median())

In [27]:
df['gender'] = df['gender'].map({
    'M':0,
    'F':1
})

In [28]:
df['gender']

0      0
1      0
2      1
3      0
4      1
      ..
115    0
116    0
117    0
118    1
119    1
Name: gender, Length: 120, dtype: int64

In [29]:
x = df.drop(columns=['churn'])

In [30]:
y = df['churn']

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train) # 데이터에 문자열이 남아있으면 안됨. id 값이 남아있어서 get_dummies 로 해결
x_test_scaled = scaler.transform(x_test)

ValueError: could not convert string to float: 'C026'

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      120 non-null    str
 1   age              120 non-null    float64
 2   gender           120 non-null    int64
 3   city             120 non-null    str
 4   monthly_fee      120 non-null    int64
 5   usage_hours      120 non-null    float64
 6   login_count      120 non-null    int64
 7   support_calls    120 non-null    int64
 8   contract_months  120 non-null    int64
 9   churn            120 non-null    int64
dtypes: float64(2), int64(6), str(2)
memory usage: 9.5 KB

In [36]:
df.head()

,customer_id,age,gender,city,monthly_fee,usage_hours,login_count,support_calls,contract_months,churn
0,C001,37.5,0,대구,40000,35.3,29,0,1,0
1,C002,58.0,0,서울,80000,9.3,12,0,3,1
2,C003,30.0,1,부산,35000,36.4,29,3,6,0
3,C004,54.0,0,울산,55000,39.0,23,2,24,0
4,C005,34.0,1,울산,40000,39.8,12,0,3,0

In [37]:
df = pd.get_dummies(df, columns=['city'])

In [38]:
df.head()

,customer_id,age,gender,monthly_fee,usage_hours,login_count,support_calls,contract_months,churn,city_대구,city_부산,city_서울,city_울산
0,C001,37.5,0,40000,35.3,29,0,1,0,True,False,False,False
1,C002,58.0,0,80000,9.3,12,0,3,1,False,False,True,False
2,C003,30.0,1,35000,36.4,29,3,6,0,False,True,False,False
3,C004,54.0,0,55000,39.0,23,2,24,0,False,False,False,True
4,C005,34.0,1,40000,39.8,12,0,3,0,False,False,False,True

In [39]:
df = df.drop(columns=['customer_id'])

In [40]:
df.head()

,age,gender,monthly_fee,usage_hours,login_count,support_calls,contract_months,churn,city_대구,city_부산,city_서울,city_울산
0,37.5,0,40000,35.3,29,0,1,0,True,False,False,False
1,58.0,0,80000,9.3,12,0,3,1,False,False,True,False
2,30.0,1,35000,36.4,29,3,6,0,False,True,False,False
3,54.0,0,55000,39.0,23,2,24,0,False,False,False,True
4,34.0,1,40000,39.8,12,0,3,0,False,False,False,True

In [41]:
x = df.drop(columns=['churn'])
y = df['churn']

In [42]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [43]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [44]:
x_train_scaled[:5]

array([[-0.33095287,  1.23544154, -1.93401343,  0.3487537 ,  0.75166354,
         0.97449632, -0.36946049, -0.48038446,  1.55838744, -0.80942721,
        -0.37796447],
       [ 0.80712983,  1.23544154,  0.58632986,  1.39189672,  0.60961688,
         0.26036161,  1.74453862, -0.48038446,  1.55838744, -0.80942721,
        -0.37796447],
       [ 1.75553207, -0.80942721,  0.58632986, -1.24770866, -2.08926952,
        -0.45377309,  0.33520588, -0.48038446,  1.55838744, -0.80942721,
        -0.37796447],
       [ 0.90197005, -0.80942721, -0.81386085,  0.92928547,  0.18347693,
        -1.1679078 , -0.72179368,  2.081666  , -0.64168895, -0.80942721,
        -0.37796447],
       [-1.56387579, -0.80942721,  0.58632986,  0.43946179, -0.24266303,
         0.26036161,  0.33520588, -0.48038446,  1.55838744, -0.80942721,
        -0.37796447]])

In [58]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [61]:
model.fit(x_train_scaled, y_train)
pred = model.predict(x_test_scaled)

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix # 정확도, 혼동행렬

cm = confusion_matrix(y_test, pred)
cm

array([[12,  2],
       [ 2,  8]])

In [52]:
accuracy = accuracy_score(y_test, pred)
accuracy

0.8333333333333334

In [ ]:
from sklearn.metrics import precision_score, recall_score # 예측 기준 1이라고 한 비율, 실제 1 중 얼마나 놓치지 않았는지 비율

precision = precision_score(y_test, pred)
precision

0.8

In [54]:
recall = recall_score(y_test, pred)
recall

0.8

In [60]:
from sklearn.metrics import f1_score # 균형 지표

f1 = f1_score(y_test, pred)
f1

0.8

In [59]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()

In [62]:
tree_model.fit(x_train, y_train)
tree_pred = tree_model.predict(x_test)

In [63]:
tree_accuracy = accuracy_score(y_test, tree_pred)
tree_accuracy

0.5833333333333334

In [64]:
tree_precision = precision_score(y_test, tree_pred)
tree_precision

0.5

In [65]:
tree_recall = recall_score(y_test, tree_pred)
tree_recall

0.7

In [66]:
tree_f1 = f1_score(y_test, tree_pred)
tree_f1

0.5833333333333334

In [68]:
tree_cm = confusion_matrix(y_test, tree_pred)
tree_cm

array([[7, 7],
       [3, 7]])

In [69]:
tree_model_3 = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

In [70]:
tree_model_3.fit(x_train, y_train)
tree_pred_3 = tree_model_3.predict(x_test)

In [72]:
tree_3_accuracy = accuracy_score(y_test, tree_pred_3)
tree_3_accuracy

0.5

In [74]:
for depth in range(1,11):
    range_model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    range_model.fit(x_train, y_train)
    pred_depth = range_model.predict(x_test)

    acc = accuracy_score(y_test, pred_depth)

    print(depth, acc)

1 0.4166666666666667
2 0.5416666666666666
3 0.5
4 0.5833333333333334
5 0.5416666666666666
6 0.5833333333333334
7 0.5833333333333334
8 0.5416666666666666
9 0.5416666666666666
10 0.5416666666666666

In [75]:
from sklearn.model_selection import cross_val_score

cv_score = cross_val_score(
    DecisionTreeClassifier(max_depth=4, random_state=42),
    x_train,
    y_train,
    cv=5,
    scoring='accuracy'
)

cv_score

array([0.5       , 0.57894737, 0.57894737, 0.47368421, 0.52631579])

In [76]:
cv_score.mean()

np.float64(0.531578947368421)

In [79]:
best_depth = None
best_score = 0

for depth in range(1, 11):

    # 모델 생성
    range_model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    # cross validation
    scores = cross_val_score(
        range_model,
        x_train,
        y_train,
        cv=5,
        scoring='accuracy'
    )

    mean_score = scores.mean()

    # best_score와 현재 평균 점수를 비교해서 best_score에 큰 값을 넣는다. 해당 depth 도 가장 최적으로 분류되어 대입시켜준다.
    if mean_score > best_score:
        best_score = mean_score
        best_depth = depth

print('best_depth :', best_depth)
print('best_score :', best_score)

best_depth : 6
best_score : 0.5531578947368421

In [82]:
# final_tree 학습
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

final_model = DecisionTreeClassifier(
    max_depth=6,
    random_state=42
)

final_model.fit(x_train, y_train)
final_pred = final_model.predict(x_test)

final_accuracy = accuracy_score(y_test, final_pred)

final_accuracy

0.5833333333333334