In [29]:
import pandas as pd

data = pd.read_csv('day18_full_review.csv')

data.head()

,customer_id,order_datetime,age,region,channel,membership_level,visit_count,session_time_min,cart_value,discount_pct,payment_method,campaign,order_amount
0,C00001,2026-06-13 09:00:00,48.0,Gwangju,web,silver,8,18.9,182.3,20,card,none,194.3
1,C00002,2026-01-07 16:00:00,52.0,Daegu,web,silver,9,26.6,72.5,15,card,summer,114.2
2,C00003,2026-03-29 12:00:00,55.0,Daegu,app,silver,16,15.4,123.1,0,card,summer,150.6
3,C00004,2026-04-07 09:00:00,31.0,Busan,store,basic,1,12.8,34.8,15,mobile,none,47.0
4,C00005,2026-03-16 09:00:00,53.0,Busan,app,basic,1,11.4,141.1,5,mobile,none,163.9

In [30]:
print(data.shape)
print(data.isnull().sum())

(435, 13)
customer_id          0
order_datetime       0
age                 15
region              12
channel              0
membership_level     0
visit_count          0
session_time_min    18
cart_value          15
discount_pct         0
payment_method      10
campaign             0
order_amount         0
dtype: int64

In [31]:
data.describe()

              age  visit_count  cart_value  discount_pct  order_amount
count  420.000000   435.000000  420.000000    435.000000    435.000000
mean    38.526190     7.896552  109.958810      9.057471    142.678391
std     11.627134     4.071466   67.029586      7.689775     44.174569
min     18.000000     1.000000    5.000000      0.000000     19.600000
25%     30.000000     5.000000   69.075000      0.000000    111.700000
50%     39.000000     8.000000  105.550000     10.000000    143.400000
75%     46.250000    11.000000  139.150000     15.000000    172.600000
max     76.000000    21.000000  518.700000     20.000000    254.100000

In [32]:
data.isnull().sum().sum()

np.int64(70)

In [33]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       435 non-null    str
 1   order_datetime    435 non-null    str
 2   age               420 non-null    float64
 3   region            423 non-null    str
 4   channel           435 non-null    str
 5   membership_level  435 non-null    str
 6   visit_count       435 non-null    int64
 7   session_time_min  417 non-null    str
 8   cart_value        420 non-null    float64
 9   discount_pct      435 non-null    int64
 10  payment_method    425 non-null    str
 11  campaign          435 non-null    str
 12  order_amount      435 non-null    float64
dtypes: float64(3), int64(2), str(8)
memory usage: 44.3 KB

In [34]:
data['membership_level'].value_counts()

membership_level
basic     197
silver    152
gold       86
Name: count, dtype: int64

In [35]:
# session_time_min 숫자로 변환
data['session_time_min'] = pd.to_numeric(data['session_time_min'], errors='coerce') # errors='coerce' : 숫자로 못바꾸는 문자열은 nan
data['session_time_min'].dtype # 실수형으로 바뀜

dtype('float64')

In [36]:
# data['age'].fillna(data['age'].median(), inplace=True)
# data['session_time_min'].fillna(data['session_time_min'].median(), inplace=True)
# data['cart_value'].fillna(data['cart_value'].mean(), inplace=True)
# data['region'].fillna(data['region'].mode()[0], inplace=True)
# data['payment_method'].fillna(data['payment_method'].mode()[0], inplace=True )

# 꼭 inplace를 여러 개 써야하는 상황이라면, DataFrame 사용({})
data.fillna({
    'age':data['age'].median(),
    'session_time_min':data['session_time_min'].median(),
    'cart_value':data['cart_value'].mean(),
    'region':data['region'].mode()[0],
    'payment_method':data['payment_method'].mode()[0]
}, inplace=True)

data.isnull().sum()

customer_id         0
order_datetime      0
age                 0
region              0
channel             0
membership_level    0
visit_count         0
session_time_min    0
cart_value          0
discount_pct        0
payment_method      0
campaign            0
order_amount        0
dtype: int64

In [37]:
# 중복행 처리
data.duplicated().sum()
data.shape

(435, 13)

In [38]:
data.drop_duplicates(inplace=True)
print(data.shape)

(430, 13)

In [ ]:
data.reset_index(drop=True, inplace=True) #drop=True를 하지 않으면 index 컬럼이 생긴다.

In [43]:
data['order_datetime'] = pd.to_datetime(data['order_datetime'])

data['order_year'] = data['order_datetime'].dt.year
data['order_month'] = data['order_datetime'].dt.month
data['order_day'] = data['order_datetime'].dt.day
data['order_hour'] = data['order_datetime'].dt.hour
data['order_dayofweek'] = data['order_datetime'].dt.dayofweek
data['is_weekend'] = data['order_dayofweek'].isin([5,6]).astype(int)

data.drop(columns='order_datetime', inplace=True)

In [44]:
data.head()

,customer_id,age,region,channel,membership_level,visit_count,session_time_min,cart_value,discount_pct,payment_method,campaign,order_amount,order_year,order_month,order_day,order_hour,order_dayofweek,is_weekend
0,C00001,48.0,Gwangju,web,silver,8,18.9,182.3,20,card,none,194.3,2026,6,13,9,5,1
1,C00002,52.0,Daegu,web,silver,9,26.6,72.5,15,card,summer,114.2,2026,1,7,16,2,0
2,C00003,55.0,Daegu,app,silver,16,15.4,123.1,0,card,summer,150.6,2026,3,29,12,6,1
3,C00004,31.0,Busan,store,basic,1,12.8,34.8,15,mobile,none,47.0,2026,4,7,9,1,0
4,C00005,53.0,Busan,app,basic,1,11.4,141.1,5,mobile,none,163.9,2026,3,16,9,0,0

In [45]:
data.rename(columns={'membership_level':'member_level'}, inplace=True)

In [ ]:
data.rename(columns={'order_amount':'target_amount'}, inplace=True)
# 값 기준 정렬
data.sort_values('target_amount', ascending=False, inplace=True)

In [ ]:

# 주문 금액이 가장 큰 값을 가진 사용자 아이디 / 여기서 id 빼면 가장 주문 금액이 높은 행 확인
# 사실상 이미 내림차순 정렬 해서 data.iloc[0]도 가능함
print(data.loc[data['target_amount'].idxmax(), 'customer_id'])
print(data.loc[data['target_amount'].idxmax()])

C00379
customer_id          C00379
age                    26.0
region              Daejeon
channel               store
member_level          basic
visit_count              14
session_time_min       17.0
cart_value            226.9
discount_pct             10
payment_method         card
campaign               none
target_amount         254.1
order_year             2026
order_month               5
order_day                30
order_hour               13
order_dayofweek           5
is_weekend                1
Name: 378, dtype: object

In [71]:
# iloc 조건
data.iloc[
    (data['region']=='Busan')&
    (data['target_amount']>=150)
    ][['customer_id', 'region', 'member_level', 'target_amount']]

# loc 조건
data.loc[
    (data['region']=='Busan')&
    (data['target_amount']>=150),
    ['customer_id', 'region', 'member_level', 'target_amount']
]

    customer_id region member_level  target_amount
406      C00407  Busan         gold          245.6
227      C00228  Busan       silver          230.3
200      C00201  Busan        basic          224.2
23       C00024  Busan         gold          221.2
354      C00355  Busan       silver          208.0
284      C00285  Busan        basic          200.8
299      C00300  Busan       silver          198.4
209      C00210  Busan         gold          194.8
120      C00121  Busan         gold          194.2
47       C00048  Busan        basic          192.8
252      C00253  Busan         gold          189.2
15       C00016  Busan       silver          187.2
315      C00316  Busan       silver          184.4
357      C00358  Busan         gold          184.4
123      C00124  Busan       silver          183.8
170      C00171  Busan       silver          182.3
62       C00063  Busan       silver          182.0
301      C00302  Busan         gold          181.8
140      C00141  Busan        basic          179.2
408      C00409  Busan        basic          178.2
118      C00119  Busan        basic          177.5
343      C00344  Busan       silver          176.2
165      C00166  Busan        basic          174.7
218      C00219  Busan       silver          173.9
239      C00240  Busan       silver          173.0
132      C00133  Busan        basic          168.1
189      C00190  Busan         gold          167.5
107      C00108  Busan        basic          166.2
64       C00065  Busan        basic          164.4
4        C00005  Busan        basic          163.9
318      C00319  Busan         gold          163.0
341      C00342  Busan       silver          162.6
238      C00239  Busan       silver          158.6
32       C00033  Busan         gold          157.4
237      C00238  Busan         gold          155.5
338      C00339  Busan       silver          152.8
127      C00128  Busan        basic          151.9
388      C00389  Busan       silver          151.7

In [80]:
# groupby 집계함수를 컬럼마다 다르게 설정 - agg 이용 - 키 밸류 형태로 들어감
region_summary = data.groupby('region').agg({
    'target_amount':'mean',
    'cart_value':'mean',
    'visit_count':'sum'
})
region_summary.sort_values('target_amount',ascending=False, inplace=True)

In [81]:
region_summary

         target_amount  cart_value  visit_count
region
Seoul       145.956790  107.666884          650
Busan       144.063636  113.687232          704
Gwangju     142.764103  108.643513          685
Daegu       141.785185  117.561946          606
Daejeon     140.904902  105.105075          747

In [82]:
region_info = pd.DataFrame({
    'region': ['Seoul', 'Busan', 'Daegu', 'Daejeon', 'Gwangju'],
    'region_grade': ['A', 'A', 'B', 'B', 'C']
})

In [84]:
# merge() - on = 조인 컬럼명
data_merged = data.merge(region_info, on='region', how='left')
data_merged.isnull().sum()

customer_id         0
age                 0
region              0
channel             0
member_level        0
visit_count         0
session_time_min    0
cart_value          0
discount_pct        0
payment_method      0
campaign            0
target_amount       0
order_year          0
order_month         0
order_day           0
order_hour          0
order_dayofweek     0
is_weekend          0
region_grade        0
dtype: int64

In [85]:
# 양방향 concat
extra_rows = data.head(3).copy()
extra_rows['customer_id'] = ['NEW001', 'NEW002', 'NEW003']

In [86]:
extra_rows

,customer_id,age,region,channel,member_level,visit_count,session_time_min,cart_value,discount_pct,payment_method,campaign,target_amount,order_year,order_month,order_day,order_hour,order_dayofweek,is_weekend
378,NEW001,26.0,Daejeon,store,basic,14,17.0,226.9,10,card,none,254.1,2026,5,30,13,5,1
137,NEW002,41.0,Daejeon,app,silver,11,16.9,220.8,0,mobile,summer,247.4,2026,4,1,17,2,0
71,NEW003,46.0,Seoul,store,gold,6,16.0,210.9,10,transfer,vip,247.1,2026,5,22,8,4,0

In [87]:
data_concat_row = pd.concat([data, extra_rows], axis=0, ignore_index=True)

In [93]:
data_concat_row.shape

(433, 18)

In [99]:
extra_cols = pd.DataFrame({
    'score_a': range(len(data)),
    'score_b': range(1000, 1000 + len(data))
})

In [95]:
data_concat_col = pd.concat([data, extra_cols], axis=1)

In [98]:
data_concat_col.shape

(430, 20)