In [1]:
import pandas as pd

df = pd.read_csv('aice_multiclass_onehot_practice.csv')

df.head()

,customer_id,signup_date,age,monthly_spend,visits_per_month,support_calls,membership_type,region,device,satisfaction_score,target_segment
0,OH0273,2021-04-05,28.0,97.30,13,1,Silver,Daejeon,Web,3.6,Gold
1,OH0435,2024-01-17,40.0,98.37,9,2,VIP,Daegu,Android,4.9,Platinum
2,OH0120,2023-09-27,42.0,170.92,7,2,Silver,Seoul,Web,2.9,Silver
3,OH0420,2021-03-25,52.0,226.54,13,3,VIP,Busan,iOS,2.8,Platinum
4,OH0155,2021-12-25,18.0,111.23,14,3,Gold,Daejeon,iOS,4.7,Platinum

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 632 entries, 0 to 631
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         632 non-null    str
 1   signup_date         632 non-null    str
 2   age                 612 non-null    float64
 3   monthly_spend       616 non-null    float64
 4   visits_per_month    632 non-null    int64
 5   support_calls       632 non-null    int64
 6   membership_type     614 non-null    str
 7   region              632 non-null    str
 8   device              632 non-null    str
 9   satisfaction_score  632 non-null    float64
 10  target_segment      632 non-null    str
dtypes: float64(3), int64(2), str(6)
memory usage: 54.4 KB

In [4]:
df.isnull().sum()

customer_id            0
signup_date            0
age                   20
monthly_spend         16
visits_per_month       0
support_calls          0
membership_type       18
region                 0
device                 0
satisfaction_score     0
target_segment         0
dtype: int64

In [5]:
df.describe()

,age,monthly_spend,visits_per_month,support_calls,satisfaction_score
count,612.000000,616.000000,632.000000,632.000000,632.000000
mean,40.624183,158.079237,11.814873,2.090190,3.482595
std,12.888770,157.164803,8.026436,1.623841,0.793424
min,18.000000,10.000000,1.000000,0.000000,1.200000
25%,32.750000,106.910000,8.000000,1.000000,2.900000
50%,40.000000,146.615000,11.000000,2.000000,3.500000
75%,48.000000,185.152500,15.000000,3.000000,4.100000
max,115.000000,2500.000000,90.000000,8.000000,5.000000

In [ ]:
# 중복행 제거

df[df.duplicated()]

df_original = df.copy()

df = df.drop_duplicates()

Empty DataFrame
Columns: [customer_id, signup_date, age, monthly_spend, visits_per_month, support_calls, membership_type, region, device, satisfaction_score, target_segment]
Index: []