In [ ]:
import numpy as np 

# 넘파이 데이터 만들기
a = np.array([1,2,3,4,5])
b = np.array(['대한민국','포르투갈','가나','우루과이'])
c = np.array([1,2,'대한민국','포르투갈'])

# 출력
print(a) # 정수
print(b) # 문자형
print(c) # 혼합 = 문자형

[1 2 3 4 5]
['대한민국' '포르투갈' '가나' '우루과이']
['1' '2' '대한민국' '포르투갈']

In [2]:
import pandas as pd 

s = pd.Series(['대한민국','포르투갈','가나','우루과이'], index=['가','나','다','라'], name='2022 카타르월드컵 H조')

print(s)

가    대한민국
나    포르투갈
다      가나
라    우루과이
Name: 2022 카타르월드컵 H조, dtype: str

In [ ]:
# 딕셔너리 형으로 데이터 프레임 생성
# DataFrame = 2차원 형태로 데이터 분석에 가장 많이 사용됨
a1 = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
a1

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [5]:
# 리스트 형으로 데이터 프레임 생성
a2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],['a','b','c'])
a2

   0  1  2
a  1  2  3
b  4  5  6
c  7  8  9

In [9]:
flight = pd.read_csv("C:/Users/LSG/Desktop/AICE_자료/Clean_Dataset.csv/Clean_Dataset.csv", encoding='cp949')
flight.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
# csv 생성됨
a2.to_csv('./result_a.csv')

In [13]:
result = pd.read_csv('./result_a.csv', encoding='cp949')
result

  Unnamed: 0  0  1  2
0          a  1  2  3
1          b  4  5  6
2          c  7  8  9

In [ ]:
# 함수 파라미터를 활용하여 원하는 컬럼만 가지고 데이터 프레임 만들기 
# 인덱스도 지정 가능 / usecols 에도 인덱스로 쓰려는 컬럼 넣어줘야 함
flight2 = pd.read_csv('C:/Users/LSG/Desktop/AICE_자료/Clean_Dataset.csv/Clean_Dataset.csv', index_col='stops', usecols=['stops', 'departure_time', 'arrival_time', 'destination_city'])
flight2

      departure_time   arrival_time destination_city
stops
zero         Evening          Night           Mumbai
zero   Early_Morning        Morning           Mumbai
zero   Early_Morning  Early_Morning           Mumbai
zero         Morning      Afternoon           Mumbai
zero         Morning        Morning           Mumbai
...              ...            ...              ...
one          Morning        Evening        Hyderabad
one        Afternoon          Night        Hyderabad
one    Early_Morning          Night        Hyderabad
one    Early_Morning        Evening        Hyderabad
one          Morning        Evening        Hyderabad

[300153 rows x 3 columns]

In [ ]:
# 범주형 데이터 2개를 비교 분석할 때 사용 
# 말 그대로 index로 쓸 컬럼, column으로 쓸 컬럼을 지정
pd.crosstab(index=flight.source_city, columns=flight.arrival_time)

arrival_time  Afternoon  Early_Morning  Evening  Late_Night  Morning  Night
source_city
Bangalore          6992           3154    14493        2673    10411  14338
Chennai            5152           1606    10830        1999     7106  12007
Delhi              8007           5262    14630        2143    13007  18294
Hyderabad          4816           1581    10539        2092     8854  12924
Kolkata            5941           2156    11304        2414     9595  14937
Mumbai             7231           1658    16527        2680    13762  19038

In [ ]:
# flight.head(10) 과 동일한 동작을 함
flight.head(n=10)

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954

In [21]:
flight.shape

(300153, 12)

In [24]:
flight.columns

Index(['Unnamed: 0', 'airline', 'flight', 'source_city', 'departure_time',
       'stops', 'arrival_time', 'destination_city', 'class', 'duration',
       'days_left', 'price'],
      dtype='str')

In [25]:
flight.dtypes

Unnamed: 0            int64
airline                 str
flight                  str
source_city             str
departure_time          str
stops                   str
arrival_time            str
destination_city        str
class                   str
duration            float64
days_left             int64
price                 int64
dtype: object

In [26]:
flight['source_city'].value_counts()

source_city
Delhi        61343
Mumbai       60896
Bangalore    52061
Kolkata      46347
Hyderabad    40806
Chennai      38700
Name: count, dtype: int64

In [ ]:
# 하나의 컬럼만 지정하여 추출 
flight[['departure_time']]

       departure_time
0             Evening
1       Early_Morning
2       Early_Morning
3             Morning
4             Morning
...               ...
300148        Morning
300149      Afternoon
300150  Early_Morning
300151  Early_Morning
300152        Morning

[300153 rows x 1 columns]

In [ ]:
# 다중 지정도 가능
flight[['flight', 'airline']]

         flight   airline
0       SG-8709  SpiceJet
1       SG-8157  SpiceJet
2        I5-764   AirAsia
3        UK-995   Vistara
4        UK-963   Vistara
...         ...       ...
300148   UK-822   Vistara
300149   UK-826   Vistara
300150   UK-832   Vistara
300151   UK-828   Vistara
300152   UK-822   Vistara

[300153 rows x 2 columns]

In [ ]:
# 슬라이싱
# 10번 부터 20번 인덱스 까지
flight[10:21]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
10,10,GO_FIRST,G8-392,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
11,11,GO_FIRST,G8-338,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5954
12,12,Indigo,6E-5001,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
13,13,Indigo,6E-6202,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.17,1,5955
14,14,Indigo,6E-549,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5955
15,15,Indigo,6E-6278,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
16,16,Air_India,AI-887,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.08,1,5955
17,17,Air_India,AI-665,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
18,18,AirAsia,I5-747,Delhi,Evening,one,Early_Morning,Mumbai,Economy,12.25,1,5949
19,19,AirAsia,I5-747,Delhi,Evening,one,Morning,Mumbai,Economy,16.33,1,5949
20,20,GO_FIRST,G8-266,Delhi,Early_Morning,one,Evening,Mumbai,Economy,11.75,1,5954

In [ ]:
# 0부터 시작하던 인덱스를 100부터 시작하도록 변경
# 총 300153개의 행 -> 인덱스는 100 ~ 300252
flight.index = np.arange(100, 300253)
flight

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
100,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300248,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300249,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300250,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300251,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300252,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [34]:
# loc를 이용하여 데이터프레임의 행이나 열에 레이블로 접근
flight.loc[[102, 202, 302]]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
202,102,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Economy,6.00,1,18923
302,202,Vistara,UK-879,Delhi,Evening,one,Night,Mumbai,Economy,5.33,2,13673

In [ ]:
# iloc을 이용하여 데이터프레임의 행이나 열에 인덱스로 접근
# 앞 = 바꾼 인덱스 뒤 = 데이터 자체 인덱스
flight.iloc[[2, 102, 202]]

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
202,102,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Economy,6.00,1,18923
302,202,Vistara,UK-879,Delhi,Evening,one,Night,Mumbai,Economy,5.33,2,13673

In [ ]:
# loc 사용 행과 열의 범위 지정
flight.loc[[102, 202, 302], ['airline','source_city']]

     airline source_city
102  AirAsia       Delhi
202  Vistara       Delhi
302  Vistara       Delhi

In [40]:
# iloc 사용 행과 열 범위 지정
flight.iloc[[2,102,202],[1,3]]

     airline source_city
102  AirAsia       Delhi
202  Vistara       Delhi
302  Vistara       Delhi

In [46]:
# 조건 자체를 변수로 지정할 수도 있음
price_tag = flight['price']>12000
airline_tag = flight['airline']=='Air_India'

flight_extract = flight[price_tag & airline_tag].head()
flight_extract

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
140,40,Air_India,AI-504,Delhi,Night,one,Morning,Mumbai,Economy,11.00,1,12150
141,41,Air_India,AI-502,Delhi,Afternoon,one,Morning,Mumbai,Economy,19.08,1,12150
142,42,Air_India,AI-506,Delhi,Morning,one,Morning,Mumbai,Economy,22.83,1,12150
143,43,Air_India,AI-803,Delhi,Early_Morning,one,Morning,Mumbai,Economy,26.42,1,12150
144,44,Air_India,AI-479,Delhi,Night,one,Afternoon,Mumbai,Economy,17.75,1,12215

In [48]:
# 데이터 추가하기 
flight['price2'] = flight['price'] * 2
flight.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,price2
100,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,11906
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,11906
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,11912
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,11910
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,11910

In [63]:
flight['price3'] = flight['price'] + flight['price2']
flight.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,duration2,days_left,price,price2,price3
100,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,21.7,1,5953,11906,17859
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,23.3,1,5953,11906,17859
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,21.7,1,5956,11912,17868
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,22.5,1,5955,11910,17865
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,23.3,1,5955,11910,17865

In [65]:
# 삽입 열 위치, 삽입 열 이름, 삽입 열 값 / allow_duplicates = True or Flase 기본 값은 False - True 일 경우 중복 열의 삽입을 허용
flight.insert(10, 'duration3', flight['duration']*10)
flight.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,duration3,duration2,days_left,price,price2,price3
100,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,21.7,21.7,1,5953,11906,17859
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,23.3,23.3,1,5953,11906,17859
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,21.7,21.7,1,5956,11912,17868
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,22.5,22.5,1,5955,11910,17865
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,23.3,23.3,1,5955,11910,17865

In [66]:
# 컬럼 삭제
# flight.drop(flight['price3']).head() 도 동일
flight = flight.drop('duration3', axis=1).head()

In [67]:
# axis=0을 수행하면 행 레벨로 첫 번째 행이 삭제됨
flight.drop(index=100, axis=0).head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,duration2,days_left,price,price2,price3
101,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,23.3,1,5953,11906,17859
102,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,21.7,1,5956,11912,17868
103,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,22.5,1,5955,11910,17865
104,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,23.3,1,5955,11910,17865

In [73]:
flight = pd.read_csv("C:/Users/LSG/Desktop/AICE_자료/Clean_Dataset.csv/Clean_Dataset.csv", encoding='cp949')
flight.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
# 컬럼명 변경하기 - 딕셔너리처럼 변경
flight = flight.rename(columns={'airline':'airline_name', 'source_city':'departure_city'})
flight.head()

,Unnamed: 0,airline_name,flight,departure_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [ ]:
# 내림차순 정렬
flight=flight.sort_values(by='Unnamed: 0', ascending=False)
# 오름차순 정렬
flight=flight.sort_values(by='Unnamed: 0', ascending=True)
flight

,Unnamed: 0,airline_name,flight,departure_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
flight = flight.rename(columns={'airline_name':'airline'})
# groupby 활용
airline_group = flight.groupby('airline')
airline_group

In [ ]:
# 해당 방식으로 그룹화된 데이터를 조회 가능
airline_group.groups

{'AirAsia': [2, 18, 19, 27, 48, 141, 147, 148, 157, 265, 290, 325, 435, 450, 608, 609, 623, 706, 746, 782, 783, 784, 814, 978, 993, 1085, 1088, 1133, 1210, 1248, 1261, 1284, 1323, 1341, 1343, 1461, 1466, 1483, 1526, 1583, 1685, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1728, 1759, 1760, 1761, 1762, 1866, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1947, 1972, 1974, 1976, 1977, 1991, 1992, 2083, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2167, 2194, 2196, 2264, 2265, 2292, 2305, 2350, 2351, 2352, 2353, 2354, 2355, 2397, 2422, 2423, 2443, 2444, 2465, 2484, ...], 'Air_India': [16, 17, 23, 37, 40, 41, 42, 43, 44, 49, 50, 51, 52, 53, 60, 71, 74, 75, 82, 86, 87, 96, 98, 107, 108, 110, 113, 114, 115, 117, 142, 143, 144, 145, 146, 151, 152, 162, 163, 164, 166, 168, 173, 182, 189, 191, 193, 195, 196, 197, 198, 199, 207, 211, 223, 225, 229, 236, 237, 241, 242, 243, 247, 250, 266, 267, 268, 269, 272, 280, 291, 295, 303, 309, 314, 315, 316, 319, 321, 329, 333, 343, 352, 357, 361, 362, 363, 372, 376, 379, 380, 381, 385, 387, 388, 390, 391, 392, 393, 394, ...], 'GO_FIRST': [8, 9, 10, 11, 20, 21, 22, 30, 68, 72, 101, 112, 126, 127, 128, 129, 130, 131, 149, 150, 200, 201, 208, 212, 213, 222, 232, 235, 244, 245, 257, 258, 259, 260, 270, 271, 277, 278, 281, 296, 312, 313, 317, 327, 328, 342, 366, 368, 371, 384, 389, 413, 414, 415, 416, 417, 418, 436, 437, 438, 439, 440, 441, 442, 455, 465, 469, 490, 491, 496, 497, 535, 552, 586, 587, 588, 589, 590, 591, 610, 611, 612, 613, 614, 615, 616, 617, 627, 639, 640, 646, 668, 669, 672, 673, 675, 691, 762, 763, 764, ...], 'Indigo': [12, 13, 14, 15, 24, 26, 29, 31, 54, 55, 56, 57, 58, 67, 79, 81, 132, 133, 134, 135, 136, 137, 139, 140, 158, 159, 167, 170, 171, 172, 174, 175, 180, 181, 190, 224, 226, 228, 261, 262, 263, 264, 282, 283, 284, 285, 286, 287, 292, 297, 301, 302, 307, 308, 310, 323, 324, 332, 337, 348, 353, 354, 358, 359, 360, 419, 420, 421, 422, 424, 425, 426, 427, 428, 445, 446, 447, 451, 454, 456, 457, 458, 459, 466, 479, 488, 489, 522, 524, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 625, ...], 'SpiceJet': [0, 1, 28, 38, 39, 45, 80, 118, 119, 138, 160, 161, 194, 227, 251, 252, 253, 274, 275, 294, 306, 311, 331, 398, 399, 400, 401, 402, 403, 423, 444, 448, 449, 452, 520, 540, 563, 564, 565, 566, 567, 568, 569, 570, 619, 620, 621, 622, 624, 665, 738, 739, 740, 741, 742, 743, 744, 745, 799, 800, 802, 844, 877, 898, 919, 920, 921, 922, 923, 924, 925, 971, 974, 975, 1049, 1092, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1150, 1155, 1200, 1243, 1281, 1286, 1287, 1288, 1289, 1290, 1291, 1331, 1332, 1368, 1369, 1412, ...], 'Vistara': [3, 4, 5, 6, 7, 25, 32, 33, 34, 35, 36, 46, 47, 59, 61, 62, 63, 64, 65, 66, 69, 70, 73, 76, 77, 78, 83, 84, 85, 88, 89, 90, 91, 92, 93, 94, 95, 97, 99, 100, 102, 103, 104, 105, 106, 109, 111, 116, 120, 121, 122, 123, 124, 125, 153, 154, 155, 156, 165, 169, 176, 177, 178, 179, 183, 184, 185, 186, 187, 188, 192, 202, 203, 204, 205, 206, 209, 210, 214, 215, 216, 217, 218, 219, 220, 221, 230, 231, 233, 234, 238, 239, 240, 246, 248, 249, 254, 255, 256, 273, ...]}

In [ ]:
# airline 별 데이터 수 확인
airline_group.count()

,Unnamed: 0,flight,departure_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
airline,,,,,,,,,,,
AirAsia,16098,16098,16098,16098,16098,16098,16098,16098,16098,16098,16098
Air_India,80892,80892,80892,80892,80892,80892,80892,80892,80892,80892,80892
GO_FIRST,23173,23173,23173,23173,23173,23173,23173,23173,23173,23173,23173
Indigo,43120,43120,43120,43120,43120,43120,43120,43120,43120,43120,43120
SpiceJet,9011,9011,9011,9011,9011,9011,9011,9011,9011,9011,9011
Vistara,127859,127859,127859,127859,127859,127859,127859,127859,127859,127859,127859

In [93]:
# 숫자 컬럼만 골라서 평균
airline_group.mean(numeric_only=True)

              Unnamed: 0   duration  days_left         price
airline
AirAsia     95102.971922   8.941714  27.735184   4091.072742
Air_India  162945.107007  15.504235  25.497466  23507.019112
GO_FIRST    87630.797005   8.755380  27.430415   5652.007595
Indigo     110102.972658   5.795197  26.264309   5324.216303
SpiceJet    91878.408834  12.579767  24.122850   6179.278881
Vistara    177755.288310  13.326634  25.894532  30396.536302

In [ ]:
# 특정 컬럼 값만 확인하기
airline_group.mean(numeric_only=True)[['price']]

                  price
airline
AirAsia     4091.072742
Air_India  23507.019112
GO_FIRST    5652.007595
Indigo      5324.216303
SpiceJet    6179.278881
Vistara    30396.536302

In [103]:
# 다중 인덱싱
# .mean(numeric_only=True) 를 따로 붙여도 가능
airline_group2 = flight.groupby(['airline', 'arrival_time']).mean(numeric_only=True)
airline_group2

                            Unnamed: 0   duration  days_left         price
airline   arrival_time
AirAsia   Afternoon       88816.983918   7.496335  26.980507   4206.467836
          Early_Morning   99485.108742   9.454591  27.088842   3632.676617
          Evening         80346.891383   8.628675  27.119117   4539.570963
          Late_Night     105201.948725   9.205835  29.071899   3828.437410
          Morning        107012.537642   9.934108  27.857339   3846.900653
          Night           88657.478861   8.740391  27.487202   4320.171700
Air_India Afternoon      162295.572046  15.954563  25.827142  23426.571700
          Early_Morning  138717.490455  17.037971  27.539501  18805.551542
          Evening        166211.387508  15.878056  24.942981  24459.593397
          Late_Night     166665.450239  13.214077  24.301435  28014.163158
          Morning        162496.968910  16.411557  25.655767  22792.180401
          Night          164175.090257  14.230348  25.451735  23683.386323
GO_FIRST  Afternoon       90534.220872   7.510892  27.706789   5511.206937
          Early_Morning   85682.954898  10.148961  27.533457   5537.433272
          Evening         86610.596935   8.284801  27.474795   6022.345547
          Late_Night      90382.433765   7.957369  29.245500   5306.723182
          Morning         84289.646143   9.633676  26.265846   5281.059399
          Night           87864.810293   9.087003  26.971360   5808.054728
Indigo    Afternoon      106570.254921   5.483550  26.018053   5458.553278
          Early_Morning  116218.737879   5.913914  29.270398   4107.122586
          Evening        113633.002071   6.255353  25.200587   5914.292555
          Late_Night     110790.778003   5.652350  27.798553   4989.383792
          Morning         93504.652953   4.389309  26.835436   4558.313037
          Night          114668.999528   6.176535  26.114164   5371.779781
SpiceJet  Afternoon       96337.994076  14.371315  25.279621   7116.303318
          Early_Morning   86212.106796  13.395576  20.773925   5348.022191
          Evening         97825.642908  13.826714  24.349964   7465.200285
          Late_Night     125755.550439   7.612829  23.339912   5911.436404
          Morning         88454.211881  12.866352  24.699010   5777.899010
          Night           87037.019268  11.825869  24.129980   5898.403658
Vistara   Afternoon      176534.776824  12.114402  25.469405  27905.873134
          Early_Morning  178997.086816  15.122223  26.597803  28597.738475
          Evening        178147.125191  13.679788  25.935980  31225.269687
          Late_Night     195942.545350  10.051710  26.937031  29699.180243
          Morning        177197.110088  14.913937  25.788161  30180.664694
          Night          177240.740619  12.191358  25.939596  30773.372570

In [104]:
airline_group2.loc[[('AirAsia','Evening')]]

                        Unnamed: 0  duration  days_left        price
airline arrival_time
AirAsia Evening       80346.891383  8.628675  27.119117  4539.570963

In [ ]:
# 기존 컬럼 인덱스로 설정하기
flight_index = flight.set_index(['airline','arrival_time'])
flight_index

                        Unnamed: 0   flight departure_city departure_time  \
airline  arrival_time
SpiceJet Night                   0  SG-8709          Delhi        Evening
         Morning                 1  SG-8157          Delhi  Early_Morning
AirAsia  Early_Morning           2   I5-764          Delhi  Early_Morning
Vistara  Afternoon               3   UK-995          Delhi        Morning
         Morning                 4   UK-963          Delhi        Morning
...                            ...      ...            ...            ...
         Evening            300148   UK-822        Chennai        Morning
         Night              300149   UK-826        Chennai      Afternoon
         Night              300150   UK-832        Chennai  Early_Morning
         Evening            300151   UK-828        Chennai  Early_Morning
         Evening            300152   UK-822        Chennai        Morning

                       stops destination_city     class  duration  days_left  \
airline  arrival_time
SpiceJet Night          zero           Mumbai   Economy      2.17          1
         Morning        zero           Mumbai   Economy      2.33          1
AirAsia  Early_Morning  zero           Mumbai   Economy      2.17          1
Vistara  Afternoon      zero           Mumbai   Economy      2.25          1
         Morning        zero           Mumbai   Economy      2.33          1
...                      ...              ...       ...       ...        ...
         Evening         one        Hyderabad  Business     10.08         49
         Night           one        Hyderabad  Business     10.42         49
         Night           one        Hyderabad  Business     13.83         49
         Evening         one        Hyderabad  Business     10.00         49
         Evening         one        Hyderabad  Business     10.08         49

                        price
airline  arrival_time
SpiceJet Night           5953
         Morning         5953
AirAsia  Early_Morning   5956
Vistara  Afternoon       5955
         Morning         5955
...                       ...
         Evening        69265
         Night          77105
         Night          79099
         Evening        81585
         Evening        81585

[300153 rows x 10 columns]

In [ ]:
# 다중 인덱스 세팅 후 해당 인덱스 기준으로 groupby하기 
# level[0,1] =  인덱스 0번째 레벨과 1번째 레벨을 기준으로 그룹화 - 다중 인덱스의 순서 번호 
flight_index2 = flight.set_index(['airline','arrival_time']).groupby(level=[0,1]).mean(numeric_only=True)
flight_index2

                            Unnamed: 0   duration  days_left         price
airline   arrival_time
AirAsia   Afternoon       88816.983918   7.496335  26.980507   4206.467836
          Early_Morning   99485.108742   9.454591  27.088842   3632.676617
          Evening         80346.891383   8.628675  27.119117   4539.570963
          Late_Night     105201.948725   9.205835  29.071899   3828.437410
          Morning        107012.537642   9.934108  27.857339   3846.900653
          Night           88657.478861   8.740391  27.487202   4320.171700
Air_India Afternoon      162295.572046  15.954563  25.827142  23426.571700
          Early_Morning  138717.490455  17.037971  27.539501  18805.551542
          Evening        166211.387508  15.878056  24.942981  24459.593397
          Late_Night     166665.450239  13.214077  24.301435  28014.163158
          Morning        162496.968910  16.411557  25.655767  22792.180401
          Night          164175.090257  14.230348  25.451735  23683.386323
GO_FIRST  Afternoon       90534.220872   7.510892  27.706789   5511.206937
          Early_Morning   85682.954898  10.148961  27.533457   5537.433272
          Evening         86610.596935   8.284801  27.474795   6022.345547
          Late_Night      90382.433765   7.957369  29.245500   5306.723182
          Morning         84289.646143   9.633676  26.265846   5281.059399
          Night           87864.810293   9.087003  26.971360   5808.054728
Indigo    Afternoon      106570.254921   5.483550  26.018053   5458.553278
          Early_Morning  116218.737879   5.913914  29.270398   4107.122586
          Evening        113633.002071   6.255353  25.200587   5914.292555
          Late_Night     110790.778003   5.652350  27.798553   4989.383792
          Morning         93504.652953   4.389309  26.835436   4558.313037
          Night          114668.999528   6.176535  26.114164   5371.779781
SpiceJet  Afternoon       96337.994076  14.371315  25.279621   7116.303318
          Early_Morning   86212.106796  13.395576  20.773925   5348.022191
          Evening         97825.642908  13.826714  24.349964   7465.200285
          Late_Night     125755.550439   7.612829  23.339912   5911.436404
          Morning         88454.211881  12.866352  24.699010   5777.899010
          Night           87037.019268  11.825869  24.129980   5898.403658
Vistara   Afternoon      176534.776824  12.114402  25.469405  27905.873134
          Early_Morning  178997.086816  15.122223  26.597803  28597.738475
          Evening        178147.125191  13.679788  25.935980  31225.269687
          Late_Night     195942.545350  10.051710  26.937031  29699.180243
          Morning        177197.110088  14.913937  25.788161  30180.664694
          Night          177240.740619  12.191358  25.939596  30773.372570

In [ ]:
# Aggregate로 집계하기 
# 데이터 프레임의 값을 다양하게 집계하여 한 번에 볼 수 있음
agg_index = flight.set_index(['airline', 'arrival_time']).groupby(level=[0,1]).aggregate([np.min, np.max]).head()
agg_index

                      Unnamed: 0           flight         departure_city  \
                             min     max      min     max            min
airline arrival_time
AirAsia Afternoon             27  202598  I5-1228  I5-942      Bangalore
        Early_Morning          2  193744  I5-1229  I5-996      Bangalore
        Evening            10006  205846  I5-1228  I5-991      Bangalore
        Late_Night          1693  202571  I5-1228  I5-992      Bangalore
        Morning               19  206617  I5-1228  I5-992      Bangalore

                              departure_time          stops        \
                          max            min      max   min   max
airline arrival_time
AirAsia Afternoon      Mumbai      Afternoon    Night   one  zero
        Early_Morning  Mumbai  Early_Morning    Night   one  zero
        Evening        Mumbai      Afternoon  Morning   one  zero
        Late_Night     Mumbai      Afternoon    Night   one  zero
        Morning        Mumbai  Early_Morning    Night   one  zero

                      destination_city            class          duration  \
                                   min     max      min      max      min
airline arrival_time
AirAsia Afternoon            Bangalore  Mumbai  Economy  Economy     0.92
        Early_Morning          Chennai  Mumbai  Economy  Economy     0.92
        Evening              Bangalore  Mumbai  Economy  Economy     0.92
        Late_Night           Bangalore  Mumbai  Economy  Economy     1.25
        Morning              Bangalore  Mumbai  Economy  Economy     1.00

                             days_left     price
                         max       min max   min    max
airline arrival_time
AirAsia Afternoon      18.33         1  49  1443  31917
        Early_Morning  15.50         1  49  1603  29501
        Evening        14.58         1  49  1443  31799
        Late_Night     17.33         1  49  1443  31707
        Morning        19.58         1  49  1105  26360